// Exportação centralizada de todos os services
export * from './base.service'
export * from './empresa.service'
export * from './clientes.service'
export * from './profissionais.service'
export * from './servicos.service'
export * from './agendamentos.service'
export * from './comandas.service'
export * from './caixa.service'
export * from './itensComanda.service'
export * from './movimentacoesCaixa.service'

// Exportações padrão para facilitar o uso
export { default as empresaService } from './empresa.service'
export { default as clientesService } from './clientes.service'
export { default as profissionaisService } from './profissionais.service'
export { default as servicosService } from './servicos.service'
export { default as agendamentosService } from './agendamentos.service'
export { default as usuariosService } from './usuarios.service'
export { default as comandasService } from './comandas.service'
export { default as caixaService } from './caixa.service'
export { default as itensComandaService } from './itensComanda.service'
export { default as movimentacoesCaixaService } from './movimentacoesCaixa.service'

// Exportar tipos
export type { CreateAgendamentoData, UpdateAgendamentoData, AgendamentoFilters } from './agendamentos.service'
export type { CreateClienteData, UpdateClienteData, ClienteFilters } from './clientes.service'
export type { CreateEmpresaData, UpdateEmpresaData } from './empresa.service'
export type { CreateProfissionalData, UpdateProfissionalData, ProfissionalFilters, ProfissionalComUsuario } from './profissionais.service'
export type { CreateServicoData, UpdateServicoData, ServicoFilters } from './servicos.service'
export type { CreateUsuarioData, UpdateUsuarioData } from './usuarios.service'
export type { CreateComandaData, UpdateComandaData, ComandaFilters } from './comandas.service'
export type { CreateCaixaData, FecharCaixaData } from './caixa.service'
export type { CreateItemComandaData, UpdateItemComandaData } from './itensComanda.service'
export type { CreateMovimentacaoData, MovimentacaoFilters } from './movimentacoesCaixa.service' 